#!/usr/bin/env python3
"""Build a Netscape cookies.txt for Bandcamp from cookie values pasted out of
your browser's dev tools.  No browser extension required.

Usage:
    python3 extract-cookies.py

The script prompts for each cookie value interactively and writes the result to
cookies.txt in the current directory (or a path you specify).

How to find the values
----------------------
1. Open https://bandcamp.com in a browser where you are logged in.
2. Press F12 to open dev tools.
3. Chrome / Edge : go to the **Application** tab → **Cookies** →
   ``https://bandcamp.com``.
   Firefox        : go to the **Storage** tab → **Cookies** →
   ``https://bandcamp.com``.
4. Look for the cookie names the script asks for and copy their **Value**
   column.

Only ``identity`` is strictly required; the others improve reliability.
Press Enter to skip any cookie you can't find.
"""
from __future__ import annotations

import sys
import time
from pathlib import Path

BANDCAMP_DOMAIN = ".bandcamp.com"

COOKIES = [
    {
        "name": "identity",
        "required": True,
        "help": (
            "The main auth cookie. This is the long base64-ish string — "
            "usually starts with a % or alphanumeric character."
        ),
    },
    {
        "name": "client_id",
        "required": False,
        "help": "A numeric ID. Optional but recommended.",
    },
    {
        "name": "session",
        "required": False,
        "help": "Session cookie. Optional but recommended.",
    },
    {
        "name": "js_logged_in",
        "required": False,
        "help": "Usually just '1'. Optional.",
    },
]


def prompt_cookie(info: dict) -> str | None:
    tag = "(required)" if info["required"] else "(optional, press Enter to skip)"
    print(f"\n  {info['name']}  {tag}")
    print(f"  {info['help']}")
    value = input(f"  Value: ").strip()
    return value or None


def build_cookie_line(name: str, value: str) -> str:
    # Netscape cookies.txt format:
    # domain  include_subdomains  path  secure  expiry  name  value
    expiry = str(int(time.time()) + 365 * 86400)  # 1 year from now
    return f"{BANDCAMP_DOMAIN}\tTRUE\t/\tTRUE\t{expiry}\t{name}\t{value}"


def main() -> int:
    print("=" * 60)
    print("  Bandcamp cookies.txt builder")
    print("=" * 60)
    print()
    print("Open bandcamp.com (logged in) → F12 → Application/Storage tab")
    print("→ Cookies → https://bandcamp.com")
    print("Copy the Value for each cookie name below.")

    collected: list[tuple[str, str]] = []
    for info in COOKIES:
        value = prompt_cookie(info)
        if value:
            collected.append((info["name"], value))
        elif info["required"]:
            print(f"\n  Error: '{info['name']}' is required. Cannot continue.")
            return 1

    if not collected:
        print("\nNo cookies provided. Aborting.")
        return 1

    default_path = "cookies.txt"
    print(f"\nOutput file [{default_path}]: ", end="")
    out = input().strip() or default_path
    out_path = Path(out)

    lines = ["# Netscape HTTP Cookie File", "# Generated by extract-cookies.py", ""]
    for name, value in collected:
        lines.append(build_cookie_line(name, value))
    lines.append("")

    out_path.write_text("\n".join(lines))
    print(f"\nWrote {len(collected)} cookie(s) to {out_path}")
    print()
    print("Next steps:")
    print(f"  1. Copy to the Pi:  scp {out_path} pi@<pi-address>:/tmp/")
    print("  2. Install it:")
    print("       sudo cp /tmp/cookies.txt /etc/bandcamp-plex/cookies.txt")
    print("       sudo chown bandcamp-plex:bandcamp-plex /etc/bandcamp-plex/cookies.txt")
    print("       sudo chmod 600 /etc/bandcamp-plex/cookies.txt")
    print("  3. Restart:  sudo systemctl restart bandcamp-plex")
    return 0


if __name__ == "__main__":
    sys.exit(main())
